### ISSUE TITLE
Simultaneous bundle loading

### ISSUE THREAD

**Issue by rubisco57** [lintalist/lintalist-bundles#2]
I was testing your application when I  realised that in the most recent version 1.9.6 two arbitrary bundles can not be loaded alongside without loading all of them -- is Lintalist intended to behave this way?

**Comment by lintalist** [comment]
There are various ways to load bundles:

**Configuration/settings**

* Default Bundle (default.txt usually)
* AlwaysLoadBundles (a CSV list of bundles to always load) 

This will give you the opportunity to load your default.txt and say markdown.txt and html.txt bundles. All other bundles would then by context sensitive.

**TitleMatch**

You can change the TitleMatch settings of various bundles so that they are always loaded using the same conditions e.g. always load these bundles in notepad

**Lock specific bundle**

From the Bundle menu (when Lintalist is active) you can select one bundle which will then be locked e.g. always active - you can not select multiple bundles (yet - I assume this is what you're asking)

**Load All Bundles**

From the Bundle menu or Tray menu select _Load All Bundles_ - this will load all bundles and keep them loaded (locked)

The above is already pretty flexible but you are probably asking if/how you can manually select say 3 bundles to load and keep them loaded similar to "Load All Bundles"

**Comment by lintalist** [comment]
There is the Omnisearch option when you search: 

> 2. Omnisearch query
> 
> When you start your query with a predefined character (@ by default) Lintalist will search in all bundles independent of the ones that are currently loaded or locked in the search Gui. You can define this character in the settings (OmniChar). If you don't want to use Omnisearch while typing a query simply disable it by erasing the OmniChar in the settings menu.
> 
> Query: state -> will find "state" in the currently loaded bundle(s)
> Query: @state -> will find "state" in all bundles
> 
> 3. Omnisearch shortcuts
> 
> - While search GUI is active: press F2 to toggle the Omnisearch.
> - If you press Ctrl+Capslock the search GUI is opened in Omnisearch mode (tip: use F2 to toggle). You can define the hotkey in the settings (StartOmniSearchHotkey)

see http://lintalist.github.io/#Omni

**Comment by rubisco57** [comment]
Thank you very much for your detailed answer(s). I will try to be more specific in possible future issue submissions and apply the proper terminology. My question referred indeed to the "locking" of a specific bundle.
Have a nice day and thank you for providing this useful and time saving piece of software for free!
